
spring:
  elasticsearch:
    rest:
      uris: http://192.168.192.137:9200
#  data:
#    elasticsearch:
#      cluster-name: docker-cluster
#      cluster-nodes: localhost:9300
server:
  port: 20000

#配置日志地址
logging:
  config: classpath:log/logback_dev.xml